import Koa from 'koa'
import Router from '@koa/router'
import bodyParser from 'koa-bodyparser'
import serve from 'koa-static'
import path from 'path'
import { fileURLToPath } from 'url'
// WebSocket 广播模块（消除循环依赖）
import { wsClients, broadcast, createWebSocketServer } from './wsBroadcast.js'
import db from './db.js'
import { genId } from './db.js'

// 钉钉集成
import * as dingtalk from './dingtalk/index.js'

// 增强调度器
import { EnhancedScheduler } from './scheduler/enhancedScheduler.js'
import workspaceManager from './workspace.js'
import workflowManager from './workflow.js'

// Skills 与 Memory 系统（Hermes 风格）
import * as skills from './skills.js'
import * as memory from './memory.js'

// Agent 角色定义 (oh-my-claudecode 风格)
import * as agentRoles from './agentRoles.js'

// Autopilot/Ralph 自动执行模式
import { autoPilotManager } from './autoPilot.js'

// Ultraqa QA 循环测试
import { ultraqaManager } from './ultraqa.js'

// Team 多代理团队管理
import { teamManager } from './teamManager.js'

// 任务执行器 (持续验证)
import { taskRunnerManager, builtInVerifiers } from './taskRunner.js'

// Wiki 和 Skill 沉淀 Hooks
import { initWikiSkillHooks } from './wikiSkillHooks.js'
import { buildWikiContext } from './wikiContextBuilder.js'

// Skill 执行追踪 Hooks
import { initSkillTrackingHooks } from './skillTrackingHooks.js'

// 初始化调度器
const enhancedScheduler = new EnhancedScheduler({
  maxConcurrentAgents: 5,
  pollInterval: 5000
})

// 初始化 Wiki/Skill Hooks
initWikiSkillHooks(enhancedScheduler)

// 初始化 Skill 执行追踪 Hooks（PostToolUse + Stop Hook）
initSkillTrackingHooks(enhancedScheduler)

const app = new Koa()
const router = new Router()

function serializeTask(task) {
  return enhancedScheduler.decorateTask(task)
}

function serializeTaskList(tasks = []) {
  return tasks.map(task => serializeTask(task))
}

function serializeBoard(board = {}) {
  return Object.fromEntries(
    Object.entries(board).map(([status, tasks]) => [status, serializeTaskList(tasks)])
  )
}

function serializeCompactSubTask(task) {
  if (!task) return task
  return {
    id: task.id,
    title: task.title,
    status: task.status,
    taskTag: task.taskTag,
    parentTaskId: task.parentTaskId || null,
    assignedAgentId: task.assignedAgentId || null,
    skipAsDependency: Boolean(task.skipAsDependency),
    blockedReason: task.blockedReason || null,
    updatedAt: task.updatedAt || null
  }
}

function truncateText(value, maxLength = 180) {
  const text = String(value || '').replace(/\r/g, '').trim()
  if (!text) return ''
  return text.length > maxLength ? `${text.slice(0, Math.max(0, maxLength - 1))}…` : text
}

function serializeAgentSummary(agent) {
  if (!agent) return agent
  return {
    id: agent.id,
    name: agent.name,
    role: agent.role,
    description: agent.description,
    model: agent.model,
    level: agent.level,
    capabilities: agent.capabilities || [],
    skillMode: agent.skillMode || 'all',
    allowedSkills: agent.allowedSkills || [],
    status: agent.status,
    currentTaskId: agent.currentTaskId || null,
    lastHeartbeat: agent.lastHeartbeat || null,
    createdAt: agent.createdAt || null,
    updatedAt: agent.updatedAt || null,
    sourceLabel: agent.sourceLabel || null
  }
}

function serializeWikiSummary(wiki) {
  if (!wiki) return wiki
  return {
    id: wiki.id,
    title: wiki.title,
    preview: truncateText(wiki.content, 160),
    keywords: wiki.keywords || [],
    taskTag: wiki.taskTag,
    parentTaskId: wiki.parentTaskId || null,
    createdAt: wiki.createdAt || null,
    updatedAt: wiki.updatedAt || null
  }
}

function serializeSkillSummary(skill) {
  if (!skill) return skill
  return {
    name: skill.name,
    description: truncateText(skill.description || skill.content, 180),
    version: skill.version || null,
    enabled: skill.enabled !== false,
    priority: skill.priority || 0,
    category: skill.category || null,
    sourceType: skill.sourceType || null,
    sourceLabel: skill.sourceLabel || null,
    sourceScope: skill.sourceScope || null,
    availableToClaude: skill.availableToClaude !== false,
    isAutoGenerated: Boolean(skill.isAutoGenerated),
    createdAt: skill.createdAt || null,
    updatedAt: skill.updatedAt || null,
    sourcePath: skill.sourcePath || null
  }
}

async function ensureSkillsReady(ctx) {
  const reload = String(ctx.query.reload || '').toLowerCase() === 'true'
  if (reload) {
    await skills.reloadSkills()
  } else {
    await skills.initSkills()
  }
}

function enrichWikiForResponse(wiki) {
  if (!wiki || !wiki.parentTaskId) return wiki

  const hasStructuredContext =
    wiki.sourceSummary ||
    (Array.isArray(wiki.requirementHighlights) && wiki.requirementHighlights.length > 0) ||
    (Array.isArray(wiki.decisionHighlights) && wiki.decisionHighlights.length > 0) ||
    (Array.isArray(wiki.issueHighlights) && wiki.issueHighlights.length > 0) ||
    (Array.isArray(wiki.verificationHighlights) && wiki.verificationHighlights.length > 0)

  if (hasStructuredContext) return wiki

  const parentTask = db.getTaskById(wiki.parentTaskId)
  if (!parentTask) return wiki

  const context = buildWikiContext(parentTask, (taskId) => db.getTaskById(taskId), (taskId) => db.getTaskLogs(taskId))

  return {
    ...wiki,
    sourceSummary: context.sourceSummary,
    artifactPaths: context.artifactPaths,
    generatedFromTaskIds: context.generatedFromTaskIds,
    requirementHighlights: context.requirementHighlights,
    decisionHighlights: context.decisionHighlights,
    issueHighlights: context.issueHighlights,
    verificationHighlights: context.verificationHighlights
  }
}

// 初始化钉钉 Stream 客户端
let dingtalkStream = null

// 中间件
app.use(bodyParser({
  jsonLimit: '12mb',
  formLimit: '12mb',
  textLimit: '12mb'
}))

// 静态文件服务
const __dirname = path.dirname(fileURLToPath(import.meta.url))
app.use(serve(path.join(__dirname, '../public')))

// 日志中间件
app.use(async (ctx, next) => {
  const start = Date.now()
  await next()
  console.log(`[${ctx.method}] ${ctx.url} - ${Date.now() - start}ms`)
})

// 健康检查
router.get('/health', (ctx) => {
  ctx.body = {
    status: 'ok',
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    dingtalk: dingtalk.streamClient?.enabled ? 'stream_enabled' : 'disabled'
  }
})

// ============ Agent 路由 ============

// 获取所有 Agent
router.get('/api/agents', (ctx) => {
  const reload = String(ctx.query.reload || '').toLowerCase() === 'true'
  ctx.body = { agents: db.getAgents({ reload }).map(agent => serializeAgentSummary(agent)) }
})

// 获取在线 Agent
router.get('/api/agents/online', (ctx) => {
  ctx.body = { agents: db.getOnlineAgents().map(agent => serializeAgentSummary(agent)) }
})

// 注册 Agent
router.post('/api/agents', async (ctx) => {
  const {
    name,
    role,
    description = '',
    model = '',
    level = 2,
    instructions = '',
    capabilities = [],
    skillMode = 'all',
    allowedSkills = []
  } = ctx.request.body

  if (!name) {
    ctx.status = 400
    ctx.body = { error: 'name is required' }
    return
  }

  let agent
  try {
    agent = db.createAgent({
      name,
      role: role || name,
      description,
      model,
      level,
      instructions,
      capabilities,
      skillMode,
      allowedSkills
    })
  } catch (e) {
    ctx.status = 400
    ctx.body = { error: e.message }
    return
  }

  // 钉钉通知
  try {
    await dingtalk.notifyAgentRegistered(agent)
  } catch (e) {
    console.error('[Notify] Agent registered notification failed:', e.message)
  }

  ctx.body = { agent }
})

// Agent 心跳
router.post('/api/agents/:id/heartbeat', (ctx) => {
  const { id } = ctx.params
  const agent = db.updateAgentHeartbeat(id)

  if (!agent) {
    ctx.status = 404
    ctx.body = { error: 'Agent not found' }
    return
  }

  ctx.body = { success: true, timestamp: new Date().toISOString() }
})

// 获取单个 Agent
router.get('/api/agents/:id', (ctx) => {
  const { id } = ctx.params
  db.getAgents({ reload: true })
  const agent = db.getAgentById(id)

  if (!agent) {
    ctx.status = 404
    ctx.body = { error: 'Agent not found' }
    return
  }

  ctx.body = { agent }
})

// 更新 Agent（写回 Claude Code agent 配置）
router.patch('/api/agents/:id', (ctx) => {
  const { id } = ctx.params
  const {
    name,
    role,
    description,
    model,
    level,
    instructions,
    capabilities,
    skillMode,
    allowedSkills
  } = ctx.request.body

  try {
    const agent = db.updateAgent(id, {
      name,
      role,
      description,
      model,
      level,
      instructions,
      capabilities,
      skillMode,
      allowedSkills
    })

    if (!agent) {
      ctx.status = 404
      ctx.body = { error: 'Agent not found' }
      return
    }

    ctx.body = { agent }
  } catch (e) {
    ctx.status = 400
    ctx.body = { error: e.message }
  }
})

// ============ Task 路由 ============

// 获取所有任务
router.get('/api/tasks', (ctx) => {
  const { status, agentId } = ctx.query

  ctx.body = { tasks: serializeTaskList(db.getTasks({ status, agentId })) }
})

// 获取看板视图
router.get('/api/board', (ctx) => {
  ctx.body = { board: serializeBoard(db.getBoard()) }
})

// 创建任务
router.post('/api/tasks', async (ctx) => {
  const {
    title,
    description,
    skills = [],
    operationFolder = '',
    maxDecompositionDepth
  } = ctx.request.body
  const requestedMaxDepth = Number.parseInt(maxDecompositionDepth, 10)

  if (!title) {
    ctx.status = 400
    ctx.body = { error: 'title is required' }
    return
  }

  const task = db.createTask({
    title,
    description,
    skills,
    operationFolder: String(operationFolder || '').trim(),
    maxDecompositionDepth: Number.isInteger(requestedMaxDepth) && requestedMaxDepth > 0
      ? requestedMaxDepth
      : undefined
  })

  // 钉钉通知
  try {
    await dingtalk.notifyTaskCreated(task)
  } catch (e) {
    console.error('[Notify] Task created notification failed:', e.message)
  }

  ctx.body = { task: serializeTask(task) }
})

// 删除任务
router.delete('/api/tasks/:id', (ctx) => {
  const { id } = ctx.params
  const success = db.deleteTask(id)

  if (!success) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  ctx.body = { success: true }
})

// 获取单个任务
router.get('/api/tasks/:id', (ctx) => {
  const { id } = ctx.params
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  ctx.body = { task: serializeTask(task) }
})

// 获取任务消息
router.get('/api/tasks/:id/messages', (ctx) => {
  const { id } = ctx.params
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  ctx.body = { messages: db.getTaskMessages(id) }
})

// 发送任务消息
router.post('/api/tasks/:id/messages', async (ctx) => {
  const { id } = ctx.params
  const { content } = ctx.request.body || {}

  if (!content || !String(content).trim()) {
    ctx.status = 400
    ctx.body = { error: 'content is required' }
    return
  }

  try {
    const result = await enhancedScheduler.handleUserMessage(id, content)
    ctx.body = {
      ...result,
      task: result.task ? serializeTask(result.task) : result.task,
      sourceTask: result.sourceTask ? serializeTask(result.sourceTask) : result.sourceTask,
      followUpTask: result.followUpTask ? serializeTask(result.followUpTask) : result.followUpTask
    }
  } catch (error) {
    const message = error?.message || 'Failed to send task message'
    if (message === 'Task not found') {
      ctx.status = 404
      ctx.body = { error: message }
      return
    }

    ctx.status = 500
    ctx.body = { error: message }
  }
})

router.get('/api/tasks/:id/live-session', (ctx) => {
  const { id } = ctx.params
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  ctx.body = enhancedScheduler.getTaskRuntimeState(id)
})

router.post('/api/tasks/:id/live-session/message', async (ctx) => {
  const { id } = ctx.params
  const { content, preferredAgentId } = ctx.request.body || {}

  if (!content || !String(content).trim()) {
    ctx.status = 400
    ctx.body = { error: 'content is required' }
    return
  }

  try {
    const result = await enhancedScheduler.handleLiveUserMessage(id, content, { preferredAgentId })
    ctx.body = {
      ...result,
      task: result.task ? serializeTask(result.task) : result.task
    }
  } catch (error) {
    const message = error?.message || 'Failed to send live task message'
    ctx.status = message === 'Task not found' ? 404 : 500
    ctx.body = { error: message }
  }
})

router.post('/api/tasks/:id/live-session/stop', async (ctx) => {
  const { id } = ctx.params

  try {
    const result = await enhancedScheduler.stopLiveSession(id, 'user_stopped')
    if (!result.success) {
      ctx.status = 400
      ctx.body = { error: 'Live session is not active' }
      return
    }

    ctx.body = {
      ...result,
      task: result.task ? serializeTask(result.task) : result.task
    }
  } catch (error) {
    ctx.status = 500
    ctx.body = { error: error?.message || 'Failed to stop live session' }
  }
})

// 获取任务输出行（终端风格信息流）
router.get('/api/tasks/:id/output', (ctx) => {
  const { id } = ctx.params
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  ctx.body = { outputLines: task.outputLines || [], currentOutput: task.currentOutput || '' }
})

// 更新任务状态
router.patch('/api/tasks/:id/status', async (ctx) => {
  const { id } = ctx.params
  const { status, operatorId, note } = ctx.request.body

  if (!status) {
    ctx.status = 400
    ctx.body = { error: 'status is required' }
    return
  }

  const result = db.updateTaskStatus(id, status, operatorId)
  if (!result) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  const { task, fromStatus } = result

  // 记录日志（测试通过/失败等操作记录）
  const actionLabels = {
    'ReadyForTest': '开发完成',
    'ReadyForDeploy': '测试通过',
    'InFix': '待修复',
    'Done': '任务完成',
    'InDev': '开始开发',
    'Collecting': '补充信息',
    'Analyzing': '开始分析'
  }
  const action = actionLabels[status] || '状态变更'
  db.addTaskLog(id, {
    agentId: operatorId || null,
    action: action,
    message: note || `${fromStatus} → ${status}`
  })

  if (['Done', 'ReadyForTest', 'InFix', 'Backlog'].includes(status)) {
    enhancedScheduler.requestImmediateSchedule(`task status updated ${fromStatus} -> ${status}`)
  }

  // 钉钉通知
  try {
    await dingtalk.notifyTaskStatusChanged(task, fromStatus, status, operatorId)
  } catch (e) {
    console.error('[Notify] Task status notification failed:', e.message)
  }

  ctx.body = { task: serializeTask(task) }
})

router.post('/api/tasks/:id/reopen', async (ctx) => {
  const { id } = ctx.params
  const { note, operatorId, status } = ctx.request.body || {}

  const task = db.reopenTask(id, {
    note,
    operatorId,
    status: status || 'Backlog'
  })

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  enhancedScheduler.requestImmediateSchedule(`task reopened ${id}`)
  ctx.body = { task: serializeTask(task) }
})

router.post('/api/tasks/:id/skip', async (ctx) => {
  const { id } = ctx.params
  const { reason, operatorId } = ctx.request.body || {}

  const task = db.skipTaskAsDependency(id, {
    reason,
    operatorId
  })

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found or task is not a subtask' }
    return
  }

  enhancedScheduler.requestImmediateSchedule(`task skipped as dependency ${id}`)
  ctx.body = { task: serializeTask(task) }
})

router.post('/api/tasks/:id/import-artifact', async (ctx) => {
  const { id } = ctx.params
  const { sourcePath, targetPath = '' } = ctx.request.body || {}
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  if (!sourcePath || !String(sourcePath).trim()) {
    ctx.status = 400
    ctx.body = { error: 'sourcePath is required' }
    return
  }

  try {
    const workspaceConfig = workflowManager.getWorkspaceConfig()
    const workspaceResult = await workspaceManager.createWorkspace(id, {
      afterCreate: workspaceConfig.hooks?.afterCreate
    })
    db.updateTaskWorkspace(id, {
      path: path.resolve(workspaceResult.path),
      status: task.status === 'Blocked' ? 'blocked' : (task.workspace?.status || 'retained_for_fix'),
      retainedForQa: false,
      cleanedAt: null
    })

    const artifact = workspaceManager.importArtifact(id, sourcePath, targetPath)
    enhancedScheduler.captureTaskArtifacts(id, workspaceResult.path)
    db.addTaskLog(id, {
      action: '人工导入工件',
      message: `${artifact.sourcePath} -> ${artifact.relativeDestinationPath}`
    })
    db.appendTaskOutput(id, `[系统] 已导入工件 ${artifact.relativeDestinationPath}`)

    ctx.body = {
      task: serializeTask(db.getTaskById(id)),
      artifact
    }
  } catch (error) {
    ctx.status = 400
    ctx.body = { error: error.message || 'Failed to import artifact' }
  }
})

router.post('/api/tasks/:id/upload-artifact', async (ctx) => {
  const { id } = ctx.params
  const {
    filename,
    contentBase64,
    targetPath = ''
  } = ctx.request.body || {}
  const task = db.getTaskById(id)

  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  if (!filename || !String(filename).trim()) {
    ctx.status = 400
    ctx.body = { error: 'filename is required' }
    return
  }

  if (!contentBase64 || !String(contentBase64).trim()) {
    ctx.status = 400
    ctx.body = { error: 'contentBase64 is required' }
    return
  }

  try {
    const workspaceConfig = workflowManager.getWorkspaceConfig()
    const workspaceResult = await workspaceManager.createWorkspace(id, {
      afterCreate: workspaceConfig.hooks?.afterCreate
    })
    db.updateTaskWorkspace(id, {
      path: path.resolve(workspaceResult.path),
      status: task.status === 'Blocked' ? 'blocked' : (task.workspace?.status || 'retained_for_fix'),
      retainedForQa: false,
      cleanedAt: null
    })

    const artifact = workspaceManager.writeArtifactContent(id, filename, contentBase64, targetPath)
    enhancedScheduler.captureTaskArtifacts(id, workspaceResult.path)
    db.addTaskLog(id, {
      action: '人工上传工件',
      message: `${filename} -> ${artifact.relativeDestinationPath}`
    })
    db.appendTaskOutput(id, `[系统] 已上传工件 ${artifact.relativeDestinationPath}`)

    ctx.body = {
      task: serializeTask(db.getTaskById(id)),
      artifact
    }
  } catch (error) {
    ctx.status = 400
    ctx.body = { error: error.message || 'Failed to upload artifact' }
  }
})

// 认领任务
router.post('/api/tasks/:id/claim', async (ctx) => {
  const { id } = ctx.params
  const { agentId } = ctx.request.body

  if (!agentId) {
    ctx.status = 400
    ctx.body = { error: 'agentId is required' }
    return
  }

  const result = db.claimTask(id, agentId)
  if (!result) {
    ctx.status = 404
    ctx.body = { error: 'Task not found or already assigned' }
    return
  }

  const { task, agent } = result

  // 钉钉通知
  try {
    await dingtalk.notifyTaskClaimed(task, agent)
  } catch (e) {
    console.error('[Notify] Task claimed notification failed:', e.message)
  }

  ctx.body = { task: serializeTask(task) }
})

// 报告 Bug
router.post('/api/tasks/:id/bug', async (ctx) => {
  const { id } = ctx.params
  const { bugReport } = ctx.request.body

  if (!bugReport) {
    ctx.status = 400
    ctx.body = { error: 'bugReport is required' }
    return
  }

  const result = db.reportBug(id, bugReport)
  if (!result) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  const { task, blocked, loopCount } = result

  // 钉钉通知
  try {
    await dingtalk.notifyBugReported(task, bugReport, loopCount)
  } catch (e) {
    console.error('[Notify] Bug report notification failed:', e.message)
  }

  ctx.body = { task, blocked, loopCount }
})

// ============ 日志路由 ============

// 获取任务历史（状态流转记录）
router.get('/api/tasks/:id/history', (ctx) => {
  const { id } = ctx.params
  ctx.body = { history: db.getTaskHistory(id) }
})

// 获取子任务列表
router.get('/api/tasks/:id/subtasks', (ctx) => {
  const { id } = ctx.params
  const compact = String(ctx.query.compact || '').toLowerCase() === 'true'
  const subTasks = db.getSubTasks(id)
  const payload = compact
    ? subTasks.map(task => serializeCompactSubTask(task))
    : subTasks
  ctx.body = { subTasks: payload }
})

// 获取任务日志
router.get('/api/tasks/:id/logs', (ctx) => {
  const { id } = ctx.params
  ctx.body = { logs: db.getTaskLogs(id) }
})

// 追加日志
router.post('/api/tasks/:id/logs', (ctx) => {
  const { id } = ctx.params
  const { agentId, action, message } = ctx.request.body

  if (!action) {
    ctx.status = 400
    ctx.body = { error: 'action is required' }
    return
  }

  ctx.body = { log: db.addTaskLog(id, { agentId, action, message }) }
})

// 追加任务输出行（终端风格显示用）
router.post('/api/tasks/:id/output', (ctx) => {
  const { id } = ctx.params
  const { line } = ctx.request.body

  if (line === undefined || line === null) {
    ctx.status = 400
    ctx.body = { error: 'line is required' }
    return
  }

  ctx.body = { output: db.appendTaskOutput(id, line) }
})

// 清除任务输出
router.delete('/api/tasks/:id/output', (ctx) => {
  const { id } = ctx.params
  ctx.body = { success: db.clearTaskOutput(id) }
})

// ============ 统计路由 ============

router.get('/api/stats', async (ctx) => {
  const reload = String(ctx.query.reload || '').toLowerCase() === 'true'
  if (reload) {
    await skills.reloadSkills()
  } else {
    await skills.initSkills()
  }
  const skillStats = skills.getSkillStats()
  const stats = db.getStats()
  stats.wikiCount = db.getWikiCount()
  stats.skillCount = skillStats.total
  stats.skillPrecipitatedCount = skillStats.claudeAuto
  stats.skillAvailableCount = skillStats.claudeAvailable
  stats.skillInstalledCount = skillStats.claudeInstalled
  stats.skillProjectSyncedCount = skillStats.claudeProjectSynced
  stats.skillProjectCount = skillStats.projectLocal
  ctx.body = stats
})

// ============ Wiki 路由 ============

router.get('/api/wiki', (ctx) => {
  const wikis = db.getWikis()
  ctx.body = { wikis: wikis.map(wiki => serializeWikiSummary(wiki)), total: wikis.length }
})

router.get('/api/wiki/search', (ctx) => {
  const { query } = ctx.query
  if (!query) {
    ctx.body = { results: [], total: 0 }
    return
  }
  const wikis = db.getWikis()
  const results = wikis.filter(w =>
    w.title.includes(query) ||
    w.content.includes(query) ||
    (w.keywords && w.keywords.some(k => k.includes(query)))
  )
  ctx.body = { results, total: results.length }
})

router.get('/api/wiki/:id', (ctx) => {
  const wiki = db.getWikiById(ctx.params.id)
  if (!wiki) {
    ctx.status = 404
    ctx.body = { error: 'Wiki not found' }
    return
  }
  ctx.body = { wiki: enrichWikiForResponse(wiki) }
})

router.get('/api/wiki/by-tasktag/:taskTag', (ctx) => {
  const taskTag = parseInt(ctx.params.taskTag)
  const wiki = db.getWikiByTaskTag(taskTag)
  ctx.body = { wiki: wiki ? enrichWikiForResponse(wiki) : null }
})

// ============ Skill 沉淀路由 ============

router.get('/api/skills/沉淀', async (ctx) => {
  await skills.reloadSkills()
  const { claudeAuto } = skills.getSkillStats()
  const count = claudeAuto
  ctx.body = { count, total: count }
})

// ============ 钉钉 Webhook 测试 ============

router.post('/api/dingtalk/test', async (ctx) => {
  try {
    await dingtalk.sendMessage({
      msgtype: 'text',
      text: { content: '🧪 钉钉连接测试成功！' }
    })
    ctx.body = { success: true }
  } catch (e) {
    ctx.status = 500
    ctx.body = { success: false, error: e.message }
  }
})

// ============ 调度器状态 ============

// 获取调度器状态
router.get('/api/scheduler/status', (ctx) => {
  ctx.body = enhancedScheduler.getStatus()
})

// 启动调度器
router.post('/api/scheduler/start', (ctx) => {
  enhancedScheduler.start()
  ctx.body = { success: true }
})

// 停止调度器
router.post('/api/scheduler/stop', (ctx) => {
  enhancedScheduler.stop()
  ctx.body = { success: true }
})

// 调整容量
router.patch('/api/scheduler/capacity', (ctx) => {
  const { maxConcurrentAgents } = ctx.request.body
  if (typeof maxConcurrentAgents !== 'number' || maxConcurrentAgents < 1 || maxConcurrentAgents > 20) {
    ctx.status = 400
    ctx.body = { error: '容量必须在 1-20 之间' }
    return
  }
  const previousCapacity = enhancedScheduler.maxConcurrentAgents
  enhancedScheduler.maxConcurrentAgents = maxConcurrentAgents
  // 持久化到数据库
  db.updateSchedulerConfig({ maxConcurrentAgents })

  if (maxConcurrentAgents > previousCapacity) {
    enhancedScheduler.requestImmediateSchedule(`capacity increased ${previousCapacity} -> ${maxConcurrentAgents}`)
  }

  ctx.body = {
    success: true,
    maxConcurrentAgents,
    previousCapacity,
    schedulingTriggered: maxConcurrentAgents > previousCapacity && enhancedScheduler.running
  }
})

// ============ Skills 系统（Hermes 风格）============

// 获取所有 Skills
router.get('/api/skills', async (ctx) => {
  await ensureSkillsReady(ctx)
  ctx.body = { skills: skills.getAllSkills().map(skill => serializeSkillSummary(skill)) }
})

// 搜索 Skills
router.get('/api/skills/search', async (ctx) => {
  await ensureSkillsReady(ctx)
  const { q } = ctx.query
  if (!q) {
    ctx.status = 400
    ctx.body = { error: 'query parameter "q" is required' }
    return
  }
  ctx.body = { skills: skills.searchSkills(q) }
})

// 获取单个 Skill
router.get('/api/skills/:name', async (ctx) => {
  await ensureSkillsReady(ctx)
  const skill = skills.getSkill(ctx.params.name)
  if (!skill) {
    ctx.status = 404
    ctx.body = { error: 'Skill not found' }
    return
  }
  ctx.body = { skill }
})

// 触发 Skill
router.post('/api/skills/trigger', async (ctx) => {
  const { userMessage, skillName, config = {} } = ctx.request.body

  if (!userMessage) {
    ctx.status = 400
    ctx.body = { error: 'userMessage is required' }
    return
  }

  const result = await skills.triggerSkill({
    skillName: skillName || '',
    userMessage,
    config
  })

  ctx.body = result
})

// 获取工具 schemas
router.get('/api/skills/tools', (ctx) => {
  ctx.body = { tools: skills.getToolSchemas() }
})

// 启用/禁用 Skill
router.patch('/api/skills/:name', async (ctx) => {
  const { enabled } = ctx.request.body
  if (typeof enabled !== 'boolean') {
    ctx.status = 400
    ctx.body = { error: 'enabled (boolean) is required' }
    return
  }

  await skills.setSkillEnabled(ctx.params.name, enabled)
  ctx.body = { success: true }
})

// 创建改进笔记
router.post('/api/skills/:name/improve', async (ctx) => {
  const { note } = ctx.request.body
  if (!note) {
    ctx.status = 400
    ctx.body = { error: 'note is required' }
    return
  }

  const result = await skills.createImprovementNote(ctx.params.name, note)
  ctx.body = result
})

// 获取改进日志
router.get('/api/skills/improvement-log', (ctx) => {
  ctx.body = { log: skills.getImprovementLog() }
})

// 自然语言转 Cron
router.post('/api/skills/to-cron', (ctx) => {
  const { natural } = ctx.request.body
  if (!natural) {
    ctx.status = 400
    ctx.body = { error: 'natural is required' }
    return
  }

  ctx.body = { cron: skills.toCron(natural) }
})

// ============ Memory 系统 ==============

// 设置 Memory 上下文
router.post('/api/memory/context', (ctx) => {
  const { userId, sessionId } = ctx.request.body
  memory.setContext(userId, sessionId)
  ctx.body = { success: true }
})

// 预取记忆
router.get('/api/memory/prefetch', (ctx) => {
  const { q } = ctx.query
  if (!q) {
    ctx.status = 400
    ctx.body = { error: 'query parameter "q" is required' }
    return
  }

  ctx.body = { result: memory.prefetch(q) }
})

// 同步 Turn
router.post('/api/memory/sync', (ctx) => {
  const { userContent, assistantContent } = ctx.request.body
  memory.syncTurn(userContent, assistantContent)
  ctx.body = { success: true }
})

// 获取记忆工具
router.get('/api/memory/tools', (ctx) => {
  ctx.body = { tools: memory.getAllToolSchemas() }
})

// 发送记忆命令
router.post('/api/memory/tools/:name', (ctx) => {
  const { name } = ctx.params
  const args = ctx.request.body || {}
  const result = memory.handleToolCall(name, args)
  ctx.body = { result }
})

// ============ 钉钉 Stream 消息接收 ============

// 钉钉回调地址（用于接收钉钉服务器推送的消息）
router.post('/api/dingtalk/callback', async (ctx) => {
  const { conversationType, conversationId, chatbotCorpId, senderNick, senderStaffId, msgId, createAt, text, conversationTitle } = ctx.request.body

  console.log('[DingTalk Callback] Received:', JSON.stringify(ctx.request.body).substring(0, 200))

  // 只处理机器人收到的消息
  if (!chatbotCorpId) {
    ctx.body = { success: true }
    return
  }

  // 解析消息内容
  const content = text?.content || ''
  if (!content.startsWith('/')) {
    // 非命令消息，可以选择忽略或自动回复
    ctx.body = { success: true }
    return
  }

  // 处理命令
  try {
    await dingtalk.handleMessage({
      type: conversationType === '2' ? 'group' : 'private',
      chatId: conversationId,
      userId: senderStaffId,
      userName: senderNick,
      text: content,
      chatName: conversationTitle
    }, `http://localhost:${PORT}`)
  } catch (e) {
    console.error('[DingTalk Command] Error:', e.message)
  }

  ctx.body = { success: true }
})

// ============ Agent 角色路由 (oh-my-claudecode) ==============

// 获取所有角色
router.get('/api/roles', (ctx) => {
  ctx.body = { roles: agentRoles.getAllRoles() }
})

// 获取单个角色
router.get('/api/roles/:name', (ctx) => {
  const role = agentRoles.getRole(ctx.params.name)
  if (!role) {
    ctx.status = 404
    ctx.body = { error: 'Role not found' }
    return
  }
  ctx.body = { role }
})

// ============ Team 多代理团队路由 ==============

// 获取 Team 状态
router.get('/api/team/status', (ctx) => {
  ctx.body = teamManager.getStatus()
})

// 创建 Team (格式: 3:claude 或 2:codex:architect)
router.post('/api/team', async (ctx) => {
  const { specs, description, options = {} } = ctx.request.body

  if (!specs || !description) {
    ctx.status = 400
    ctx.body = { error: 'specs and description are required' }
    return
  }

  const task = teamManager.createTeam(specs, description, options)
  ctx.body = { task: task.getStatus() }
})

// 启动 Team
router.post('/api/team/:taskId/start', async (ctx) => {
  const task = teamManager.getTask(ctx.params.taskId)
  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Team task not found' }
    return
  }

  await task.start()
  ctx.body = { task: task.getStatus() }
})

// 关闭 Team
router.post('/api/team/:taskId/shutdown', (ctx) => {
  const success = teamManager.shutdownTask(ctx.params.taskId)
  ctx.body = { success }
})

// 获取所有 Team 任务
router.get('/api/teams', (ctx) => {
  ctx.body = { tasks: teamManager.getAllTasks() }
})

// ============ Autopilot/Ralph 自动执行路由 ==============

// 获取 Autopilot 状态
router.get('/api/autopilot/status', (ctx) => {
  ctx.body = autoPilotManager.getStatus()
})

// 创建 Autopilot 任务
router.post('/api/autopilot', (ctx) => {
  const { description, options = {} } = ctx.request.body

  if (!description) {
    ctx.status = 400
    ctx.body = { error: 'description is required' }
    return
  }

  const task = autoPilotManager.createTask(description, options)
  enhancedScheduler.requestImmediateSchedule(`autopilot created ${task.taskId}`)
  ctx.body = {
    task: task.getStatus(),
    linkedTask: task.linkedTaskId ? serializeTask(db.getTaskById(task.linkedTaskId)) : null
  }
})

// 创建 Ralph 任务 (带验证)
router.post('/api/autopilot/ralph', (ctx) => {
  const { description, options = {} } = ctx.request.body

  if (!description) {
    ctx.status = 400
    ctx.body = { error: 'description is required' }
    return
  }

  const task = autoPilotManager.createRalphTask(description, options)
  enhancedScheduler.requestImmediateSchedule(`ralph created ${task.taskId}`)
  ctx.body = {
    task: task.getStatus(),
    linkedTask: task.linkedTaskId ? serializeTask(db.getTaskById(task.linkedTaskId)) : null
  }
})

router.post('/api/autopilot/:taskId/pause', (ctx) => {
  const success = autoPilotManager.pauseTask(ctx.params.taskId)
  if (!success) {
    ctx.status = 404
    ctx.body = { error: 'Autopilot task not found' }
    return
  }

  ctx.body = { task: autoPilotManager.getTask(ctx.params.taskId)?.getStatus?.() || null }
})

router.post('/api/autopilot/:taskId/resume', (ctx) => {
  const success = autoPilotManager.resumeTask(ctx.params.taskId)
  if (!success) {
    ctx.status = 404
    ctx.body = { error: 'Autopilot task not found' }
    return
  }

  enhancedScheduler.requestImmediateSchedule(`autopilot resumed ${ctx.params.taskId}`)
  ctx.body = { task: autoPilotManager.getTask(ctx.params.taskId)?.getStatus?.() || null }
})

// 取消 Autopilot 任务
router.post('/api/autopilot/:taskId/cancel', (ctx) => {
  const success = autoPilotManager.cancelTask(ctx.params.taskId)
  if (!success) {
    ctx.status = 404
    ctx.body = { error: 'Autopilot task not found' }
    return
  }

  ctx.body = { task: autoPilotManager.getTask(ctx.params.taskId)?.getStatus?.() || null }
})

// 获取所有 Autopilot 任务
router.get('/api/autopilot/tasks', (ctx) => {
  ctx.body = { tasks: autoPilotManager.getAllTasks() }
})

// ============ Task Runner 持续验证路由 ==============

// 获取所有任务运行器状态
router.get('/api/taskrunner/status', (ctx) => {
  ctx.body = { runners: taskRunnerManager.getAllStatuses() }
})

// 获取内置验证器
router.get('/api/taskrunner/verifiers', (ctx) => {
  ctx.body = { verifiers: Object.keys(builtInVerifiers) }
})

// 创建任务运行器
router.post('/api/taskrunner/:taskId/start', async (ctx) => {
  const { taskId } = ctx.params
  const { steps = [], options = {} } = ctx.request.body

  // 检查任务是否存在
  const task = db.getTaskById(taskId)
  if (!task) {
    ctx.status = 404
    ctx.body = { error: 'Task not found' }
    return
  }

  // 创建运行器
  const runner = taskRunnerManager.create(taskId, options)

  // 设置步骤
  if (steps.length > 0) {
    runner.setSteps(steps)
  }

  // 默认步骤 (如果没有提供)
  if (runner.steps.length === 0) {
    runner.setSteps([
      { name: '开发', description: '执行开发任务', verifier: 'syntax' },
      { name: '编译', description: '编译检查', verifier: 'build' },
      { name: '测试', description: '运行测试', verifier: 'test' },
      { name: '风格检查', description: '代码风格检查', verifier: 'lint' }
    ])
  }

  // 执行器函数 (这里用模拟的，实际应该调用 AI)
  const executor = async (step, runner) => {
    return { success: true }
  }

  // 验证器函数
  const verifier = async (step, runner) => {
    const verifyFn = builtInVerifiers[step.verifier]
    if (verifyFn) {
      return await verifyFn(step, { runner })
    }
    return { passed: true, message: '跳过验证' }
  }

  // 开始执行
  const result = await runner.start(executor, verifier)

  ctx.body = {
    task: db.getTaskById(taskId),
    runner: runner.getStatus(),
    result
  }
})

// 修复完成后继续
router.post('/api/taskrunner/:taskId/resume', async (ctx) => {
  const { taskId } = ctx.params

  const runner = taskRunnerManager.get(taskId)
  if (!runner) {
    ctx.status = 404
    ctx.body = { error: 'Runner not found' }
    return
  }

  const executor = async (step, runner) => {
    return { success: true }
  }

  const verifier = async (step, runner) => {
    const verifyFn = builtInVerifiers[step.verifier]
    if (verifyFn) {
      return await verifyFn(step, { runner })
    }
    return { passed: true }
  }

  const result = await runner.resume(executor, verifier)

  ctx.body = {
    task: db.getTaskById(taskId),
    runner: runner.getStatus(),
    result
  }
})

// 完成部署
router.post('/api/taskrunner/:taskId/complete', (ctx) => {
  const { taskId } = ctx.params

  const runner = taskRunnerManager.get(taskId)
  if (!runner) {
    ctx.status = 404
    ctx.body = { error: 'Runner not found' }
    return
  }

  runner.complete()
  taskRunnerManager.remove(taskId)

  ctx.body = {
    task: db.getTaskById(taskId)
  }
})

// ============ Ultraqa QA 循环路由 ==============

// 获取 Ultraqa 状态
router.get('/api/ultraqa/status', (ctx) => {
  ctx.body = ultraqaManager.getStatus()
})

// 创建 Ultraqa 任务
router.post('/api/ultraqa', (ctx) => {
  const { goal, options = {} } = ctx.request.body

  if (!goal) {
    ctx.status = 400
    ctx.body = { error: 'goal is required' }
    return
  }

  const task = ultraqaManager.createTask(goal, options)
  ctx.body = { task: task.getStatus() }
})

// 取消 Ultraqa 任务
router.post('/api/ultraqa/:taskId/cancel', (ctx) => {
  const success = ultraqaManager.cancelTask(ctx.params.taskId)
  ctx.body = { success }
})

// 获取所有 Ultraqa 任务
router.get('/api/ultraqa/tasks', (ctx) => {
  ctx.body = { tasks: ultraqaManager.getAllTasks() }
})

// 应用路由
app.use(router.routes())
app.use(router.allowedMethods())

// 启动服务器
const PORT = process.env.PORT || 8085
const HOST = process.env.HOST || '0.0.0.0'

// 手动创建 HTTP 服务器以正确处理 WebSocket 升级
import http from 'http'
const server = http.createServer(app.callback())

// 创建 WebSocket 服务器（使用 wsBroadcast 模块）
createWebSocketServer(server)

server.listen(PORT, HOST, async () => {
  console.log(`[Server] Running on http://${HOST}:${PORT}`)
  console.log(`[Server] Data file: ${process.cwd()}/data/scheduler.json`)

  // 初始化 Skills 系统（Hermes 风格）
  await skills.initSkills()

  // 初始化 Memory 系统
  memory.initMemory()

  // 启动钉钉集成
  if (dingtalk.streamConfig.enabled) {
    console.log('[DingTalk] Stream mode enabled')
    try {
      // 设置消息处理函数
      dingtalk.streamClient.on('message', async (msg) => {
        console.log('[DingTalk Stream] Message received:', msg.text.substring(0, 50))
        await dingtalk.handleMessage(msg, `http://localhost:${PORT}`)
      })

      await dingtalk.streamClient.start()
    } catch (e) {
      console.error('[DingTalk] Failed to start stream:', e.message)
    }
  } else {
    console.log('[DingTalk] Stream mode disabled')
  }

  if (dingtalk.webhookConfig.enabled && dingtalk.webhookConfig.webhookUrl) {
    console.log('[DingTalk] Webhook mode enabled')
  } else {
    console.log('[DingTalk] Webhook mode disabled')
  }

  // 服务启动后自动恢复调度器，避免重启后待测试/待开发任务无人处理
  if (process.env.DISABLE_SCHEDULER === '1') {
    console.log('[Scheduler] Auto start disabled by DISABLE_SCHEDULER=1')
  } else {
    enhancedScheduler.start()
  }
})
